### ISSUE TITLE
Test fails because the structure of the output is different from the general structure

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/eos3ae6#8]
The output JSON structure that we generally follow across all models is:
```JSON
{
    "input": {
        "key": "string",
        "input": "string",
        "text": "string"
    },
    "output": {
        "outcome": [...]
    }
}
```

However in this model the service.py file is modified to replace the key `outcome` with `whales`. Since the test looks for the values in `outcome` field, being unable to find this key, the test fails.

**Comment by GemmaTuron** [comment]
Hi, how do we solve this?
I had to do a minor update on the versions of the packages and it is failing now to upload to Docker

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

Has this been solved?
